# WeatherStatistics Makefile by Olivia Stone for Code Clinic: C++
CC		= g++
TARGET	= main.exe
SRC		= WeatherStatisticsMain.cpp WeatherStatistics.cpp

$(TARGET): $(SRC)
	$(CC) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)